# Set-up instruction
# 1. To build and run for the first time:
#    docker-compose up --build
#    builds the images and starts the containers
#
# 2. Run the Application again:
#    docker-compose up
#
# 3. Stop running the containers:
#    docker-compose down
#
# 4. To rebuild the images:
#    docker-compose up --build

version: '3.8'
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '5000:5000'
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend/101460443_comp3133_assignment2
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - backend
    
networks:
  app-network:
    driver: bridge



